name: DockerHub

on:
  push:
    branches: [ master ]
    tags: ['*']


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ secrets.DOCKER_USER }}/hoodboot
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_KEY }}
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
      name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    -
      name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
